"""
Exclusion logic for filtering auto-generated files, build artifacts,
and respecting .gitignore patterns during project scanning.
"""

import fnmatch
import re
from pathlib import Path
from typing import List, Optional, Set, Tuple


# Directories that should always be skipped
ALWAYS_SKIP_DIRS: Set[str] = {
    # Version control
    ".git", ".svn", ".hg",
    # AI tool config (we generate these, don't scan them)
    ".cursor", ".claude", ".ai-rules",
    # Package managers / dependencies
    "node_modules", ".pnpm", "bower_components",
    # Python environments
    ".venv", "venv", "env", ".env", "__pycache__", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".tox", "*.egg-info",
    # Build outputs
    "dist", "build", "out", "_build", ".build",
    ".next", ".nuxt", ".svelte-kit", ".turbo",
    ".vercel", ".netlify", ".serverless",
    # Compiled output
    "target", "bin", "obj", "Debug", "Release",
    # Coverage / test artifacts
    "coverage", ".nyc_output", "htmlcov", ".coverage",
    # IDE
    ".idea", ".vscode", ".fleet",
    # OS files
    ".DS_Store", "Thumbs.db",
    # Storybook
    ".storybook",
    # Mobile / cross-platform
    ".expo", ".dart_tool", ".flutter-plugins", ".flutter-plugins-dependencies",
    # IaC / cloud
    ".terraform",
    # Build tools
    ".gradle", ".mvn",
    "bazel-bin", "bazel-out", "bazel-testlogs", "bazel-genfiles",
    # Caching
    ".parcel-cache", ".cache", ".sass-cache",
}

# File patterns that indicate auto-generated content
GENERATED_FILE_PATTERNS: List[str] = [
    "*.min.js", "*.min.css", "*.min.mjs",
    "*.bundle.js", "*.bundle.css",
    "*.generated.*", "*.g.dart", "*.freezed.dart",
    "*.lock", "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "*.map",  # source maps
    "*.d.ts",  # TypeScript declarations (often generated)
    "*.pyc", "*.pyo",
]

# Known auto-generated directories by context
GENERATED_DIR_PATTERNS: List[str] = [
    "generated", "__generated__", ".generated",
    "auto-generated", "autogenerated",
    # Prisma
    "prisma/generated",
    # GraphQL codegen
    "__generated__",
    # Protocol Buffers
    "pb", "proto_gen",
]

# Markers inside files that indicate auto-generation
GENERATED_FILE_MARKERS: List[str] = [
    "@generated",
    "DO NOT EDIT",
    "AUTO-GENERATED",
    "auto-generated",
    "This file is generated",
    "Generated by",
    "Code generated by",
    "AUTOGENERATED",
]

# Registry of auto-generated UI directories: (config_file, generated_dirs)
# If config_file exists in project root, the generated_dirs are auto-generated
AUTOGENERATED_UI_REGISTRY: List[Tuple[str, List[str]]] = [
    # shadcn/ui
    ("components.json", ["components/ui", "src/components/ui"]),
    # Storybook
    (".storybook", ["storybook-static"]),
]


def parse_gitignore(project_root: Path) -> List[str]:
    """Parse .gitignore file and return list of ignore patterns."""
    gitignore_path = project_root / ".gitignore"
    if not gitignore_path.exists():
        return []

    patterns = []
    try:
        content = gitignore_path.read_text(encoding="utf-8")
        for line in content.splitlines():
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith("#"):
                continue
            patterns.append(line)
    except OSError:
        pass

    return patterns


def _matches_gitignore_pattern(path_str: str, pattern: str) -> bool:
    """Check if a path matches a gitignore-style pattern."""
    # Remove trailing slash (directory indicator)
    pattern = pattern.rstrip("/")

    # Negation patterns handled separately
    if pattern.startswith("!"):
        return False

    # If pattern contains a slash, it's relative to root
    if "/" in pattern and not pattern.startswith("*"):
        return fnmatch.fnmatch(path_str, pattern) or fnmatch.fnmatch(
            path_str, f"**/{pattern}"
        )

    # Otherwise match against any path component
    parts = path_str.split("/")
    for part in parts:
        if fnmatch.fnmatch(part, pattern):
            return True

    return fnmatch.fnmatch(path_str, f"**/{pattern}")


def is_gitignored(
    path: Path, project_root: Path, gitignore_patterns: List[str]
) -> bool:
    """Check if a path matches any .gitignore pattern, with negation support."""
    if not gitignore_patterns:
        return False

    try:
        rel_path = str(path.relative_to(project_root))
    except ValueError:
        return False

    rel_path = rel_path.replace("\\", "/")

    # Two-pass approach: first check positive patterns, then negation
    matched = False
    for pattern in gitignore_patterns:
        if pattern.startswith("!"):
            # Negation: if the path matches the negated pattern, un-ignore it
            negated_pattern = pattern[1:].strip()
            if negated_pattern and _matches_gitignore_pattern(rel_path, negated_pattern):
                matched = False
        else:
            if _matches_gitignore_pattern(rel_path, pattern):
                matched = True

    return matched


def is_autogenerated_ui_dir(path: Path, project_root: Path) -> bool:
    """Check if directory is an auto-generated UI directory using the registry."""
    try:
        rel = str(path.relative_to(project_root)).replace("\\", "/")
    except ValueError:
        return False

    for config_file, generated_dirs in AUTOGENERATED_UI_REGISTRY:
        config_path = project_root / config_file
        if config_path.exists() or config_path.is_dir():
            for gen_dir in generated_dirs:
                if rel == gen_dir or rel.endswith(f"/{gen_dir}"):
                    return True

    return False


def has_shadcn_config(project_root: Path) -> bool:
    """Check if project uses shadcn (components.json exists)."""
    return (project_root / "components.json").exists()


def is_generated_file(file_path: Path) -> bool:
    """Check if a file is auto-generated by examining its first few lines."""
    try:
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            # Read first 10 lines
            head = ""
            for i, line in enumerate(f):
                if i >= 10:
                    break
                head += line

        for marker in GENERATED_FILE_MARKERS:
            if marker.lower() in head.lower():
                return True
    except (OSError, UnicodeDecodeError):
        pass

    return False


def should_skip_dir(
    dir_path: Path,
    project_root: Path,
    gitignore_patterns: Optional[List[str]] = None,
) -> bool:
    """Determine if a directory should be skipped during scanning."""
    name = dir_path.name

    # Hidden directories (except a few we handle explicitly)
    if name.startswith(".") and name not in (".github",):
        return True

    # Always-skip list
    if name in ALWAYS_SKIP_DIRS:
        return True

    # Check against generated dir patterns
    try:
        rel = str(dir_path.relative_to(project_root)).replace("\\", "/")
    except ValueError:
        rel = name

    for pattern in GENERATED_DIR_PATTERNS:
        if rel == pattern or rel.endswith(f"/{pattern}") or name == pattern:
            return True

    # Auto-generated UI directories (shadcn, storybook, etc.)
    if is_autogenerated_ui_dir(dir_path, project_root):
        return True

    # .gitignore patterns
    if gitignore_patterns and is_gitignored(dir_path, project_root, gitignore_patterns):
        return True

    return False


def should_skip_file(
    file_path: Path,
    project_root: Path,
    gitignore_patterns: Optional[List[str]] = None,
) -> bool:
    """Determine if a file should be skipped during scanning."""
    name = file_path.name

    # Check generated file patterns
    for pattern in GENERATED_FILE_PATTERNS:
        if fnmatch.fnmatch(name, pattern):
            return True

    # .gitignore patterns
    if gitignore_patterns and is_gitignored(
        file_path, project_root, gitignore_patterns
    ):
        return True

    return False


def get_exclusion_context(project_root: Path) -> dict:
    """Build exclusion context for a project root - call once, reuse during scanning."""
    gitignore_patterns = parse_gitignore(project_root)

    return {
        "gitignore_patterns": gitignore_patterns,
        "project_root": project_root,
    }
